basePath: /
definitions:
  routes.CPInfo:
    properties:
      address:
        type: string
      endpoint:
        type: string
      name:
        description: provider name
        type: string
      numCPU:
        type: string
      numGPU:
        type: string
      numMem:
        type: string
      numStore:
        type: string
      priCPU:
        type: string
      priGPU:
        type: string
      priMem:
        type: string
      priStore:
        type: string
    type: object
host: http://localhost:8002
info:
  contact: {}
  description: This is the grid platform
  title: PLATFORM API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: welcome api
      produces:
      - application/json
      responses:
        "200":
          description: file id
          schema:
            type: string
      summary: welcome
      tags:
      - Welcome
  /allowance/:
    get:
      consumes:
      - application/json
      description: check the allowance between an owner and a spender
      parameters:
      - description: owner
        in: query
        name: owner
        required: true
        type: string
      - description: spender
        in: query
        name: spender
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Check Allowance
      tags:
      - Allowance
  /cps/:
    get:
      consumes:
      - application/json
      description: get cp number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Get CP number
      tags:
      - Get CP Number
  /disk-all/:
    get:
      consumes:
      - application/json
      description: total store space
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Total Store
      tags:
      - Total Store
  /disk-used/:
    get:
      consumes:
      - application/json
      description: used store space
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Used Store
      tags:
      - Used Store
  /getcp/:
    get:
      consumes:
      - application/json
      description: get a provider's info
      parameters:
      - description: address of a provider
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.CPInfo'
        "404":
          description: page not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: get a provider
      tags:
      - Get Provider Info
  /getorder/:
    get:
      consumes:
      - application/json
      description: get an order info
      parameters:
      - description: user
        in: query
        name: user
        required: true
        type: string
      - description: cp
        in: query
        name: cp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Get Order
      tags:
      - Get Order
  /getorders/:
    get:
      consumes:
      - application/json
      description: get all orders of an user
      parameters:
      - description: user
        in: query
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Get Orders
      tags:
      - Get Orders
  /listcp/:
    get:
      consumes:
      - application/json
      description: list all providers
      parameters:
      - description: start
        in: query
        name: start
        required: true
        type: string
      - description: number
        in: query
        name: num
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.CPInfo'
            type: array
        "404":
          description: page not found
          schema:
            type: string
      summary: List all providers
      tags:
      - Listcps
  /mem-all/:
    get:
      consumes:
      - application/json
      description: total memory space
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Total Memory
      tags:
      - Total Memory
  /mem-used/:
    get:
      consumes:
      - application/json
      description: used memory space
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Used Memory
      tags:
      - Used Memory
  /node-all/:
    get:
      consumes:
      - application/json
      description: all node number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: All Node Number
      tags:
      - Node All
  /node-used/:
    get:
      consumes:
      - application/json
      description: used node number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Used Node Number
      tags:
      - Node Used
  /node/:
    get:
      consumes:
      - application/json
      description: Get a node of a cp with node id
      parameters:
      - description: cp address
        in: query
        name: cp
        required: true
        type: string
      - description: node id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Node
      tags:
      - Get Node
  /nodes/:
    get:
      consumes:
      - application/json
      description: Get all nodes of this provider
      parameters:
      - description: cp address
        in: query
        name: cp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: page not found
          schema:
            type: string
      summary: Nodes
      tags:
      - Get Nodes
  /querycredit:
    get:
      consumes:
      - application/json
      description: Query credit of someone
      parameters:
      - description: address of this caller
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: query OK
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
      summary: QueryCredit
      tags:
      - QueryCredit
  /version:
    get:
      consumes:
      - multipart/form-data
      description: get version
      produces:
      - application/json
      responses:
        "200":
          description: version OK
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
      summary: version
      tags:
      - Version
swagger: "2.0"
